apiVersion: apps/v1
kind: Deployment
metadata:
  name: dockerfile-app
  labels:
    app: Title
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dockerfile-app
  template:
    metadata:
      labels:
        app: dockerfile-app
    spec:
      containers:
        - name: dockerfile-app
          image: dockerfile:latest
          ports:
            - containerPort: 3000