apiVersion: v1
kind: Service
metadata:
  name: dockerfile-app-service
spec:
  selector:
    app: dockerfile-app-service
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 30080
  type: NodePort
  